### ISSUE TITLE
"Date de création" décalée ou "null"

### ISSUE THREAD

**Issue by jfroment** [guisalmon/pirate_sheep#1]
Hello,

Merci pour cette appli, super initiative ! Et rien de choquant dans le code, merci d'être transparent là-dessus :)
Il semble y avoir un petit bug (version 1.0.3), le lieu de création/signature du PDF ne semble pas être intégré au QRCode : la valeur est "null". (champ "Fait à").
![null](https://user-images.githubusercontent.com/2869798/78567399-eab15c00-7820-11ea-89cf-65f9cfa04bb7.png)
J'ai généré le même PDF avec le lien officiel du gouvernement, et il y a bien la valeur dans le qrcode.

Encore merci pour le taff !

Bonne journée

**Comment by guisalmon** [comment]
Le champ qui permet de remplir cette information se trouve sous la
"raison", est-il bien rempli ? Dans les deux cas c'est un bug, mais pas le
même.

Le lun. 6 avr. 2020 à 16:10, Jean Froment <notifications@github.com> a
écrit :

**Comment by jfroment** [comment]
Au temps pour moi, je viens de re-tester, il ne s'agit pas du champ "Fait à" qui se concatène à l'adresse (lui c'est OK) mais du champ "Heure de création", qui est un champ pré-rempli.

En retestant, en fait c'est plus chiadé que ça :

- Si je génère une attestation pour "tout de suite" (en laissant le champ de l'heure par défaut à l'heure présente), la valeur est "null" dans le QRCode généré.
- Si je le crée pour une heure ultérieure (mettons 20:34), le QRCode contient bien les infos pour une sortie à 20:34 mais l'heure de création affiche 20:36. J'ai retesté plusieurs fois, il y a toujours 2 minutes de plus dans le champ de l'heure de création que l'heure de sortie.

**Comment by guisalmon** [comment]
Les deux minutes c'est normal. En gros j'avais le choix entre mettre
l'heure réelle de génération du document ou une heure "réaliste" pour les
petits malins qui généreraient l'attestation à la dernière minute en
apercevant un contrôle. Comme j'ai plus de sympathie pour les petits malins
que pour la police j'ai choisi la deuxième option.
En revanche le premier point me chiffonne et je n'arrive pas à reproduire.

Le lun. 6 avr. 2020 à 16:39, Jean Froment <notifications@github.com> a
écrit :

**Comment by jfroment** [comment]
Ah je comprends mieux ! Mais ça ne devrait pas être 2 minutes avant (plutôt que après) dans ce cas-là ?
Ca serait plus réaliste, et s'il y a un contrôle à la dernière minute, ça éviterait d'avoir la date de création 1 à 2 minutes dans le futur (ça sera plus crédible si la création date de 3 ou 4 minutes dans le passé). M'enfin je vois l'idée.

Pour le "null" ça me le fait toujours, en killant l'appli ou pas, sans rien toucher aux données pré-remplies..

**Comment by guisalmon** [comment]
Les deux minutes sont décalées vers le futur car sur le formulaire officiel
l'heure de sortie est remplie à l'ouverture de la page web, celle de
création du formulaire au moment de la génération. Donc plus tard.
Je suis actuellement en train de résoudre un autre problème mais je vais
revenir sur cette histoire de champ null. Je compte refaire une version
d'ici la fin de la journée, j'espère réussir à tout résoudre d'ici-là.

Le lun. 6 avr. 2020 à 16:55, Jean Froment <notifications@github.com> a
écrit :

**Comment by jfroment** [comment]
Ok pas de soucis ! Merci encore pour tout.

**Comment by julienferga** [comment]
Bonjour à vous, 

je n'ai pas étudié le code mais le bug du champ null semble s'établir lorsqu'on ouvre l'app les fois suivantes et qu'on laisse l'heure par défaut. Tout semble correcte à l'écran (app, fichier PDF) mais à la lecteur du QR Code, la valeur "null" apparait comme indique jfroment.

Par contre, si on ouvre le sélecteur d'heure (en cliquant sur l'heure du champ "A") et qu'on valide le sélecteur sans modifier l'heure proposée, alors dans ce cas-là, le QR Code est bien valide !

Visiblement, cela ressemble à une histoire de variable qui n'est pas lu correctement... Merci en tous cas pour le partage de cette magnifique app qui semble clean et efficace !

On attend ta prochaine release Guillaume ;)

**Comment by guisalmon** [comment]
Merci c'est pile poil les infos qu'il me fallait, je vois où ça doit
merder. Je regarde ça.
