### ISSUE TITLE
traduction

### ISSUE THREAD

**Issue by goone42** [guisalmon/pirate_sheep#2]
Salut,
j'ai filé la main pour traduire les entrées de ton appli en différentes langues. J'ai testé ensuite l'appli et j'ai pas pu trouvé comment on fait pour accéder aux différentes langues. Merci

**Comment by guisalmon** [comment]
Oh désolé, comme le format du QR code a changé (voir le README) je n'ai pas
maintenu l'app ces derniers jours. J'intègre la langue sans tarder.

**Comment by guisalmon** [comment]
C'est bon, toutes les langues traduites ont été rajoutées à la 1.0.6, le lien pour télécharger la dernière version (1.0.6) est sur la page principale.

**Comment by guisalmon** [comment]
C'est bon, toutes les langues traduites ont été rajoutées à la 1.0.6, le lien pour télécharger la dernière version (1.0.6) est sur la page principale.
